package com.ynm.service.gcd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * The port type of the WSDL is the first element we
 * 			will focus on. This element is comparable
 * 			to an interface. It defines
 * 			the type or types of services that are
 * 			available. As part of
 * 			generation, the port type has been given the name Orders to uniquely
 * 			identify it
 * 			in the document.
 * 		
 *
 * This class was generated by Apache CXF 2.7.8
 * 2017-06-29T00:05:45.165+10:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://www.ynm.com/service/gcd/", name = "GCDInterface")
@XmlSeeAlso({com.ynm.schema.gcd.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GCDInterface {

    @WebResult(name = "gcdValueList", targetNamespace = "http://www.ynm.com/schema/gcd", partName = "GCDValueListResponse")
    @WebMethod(action = "http://www.pluralsight.com/service/gcd/getlist")
    public com.ynm.schema.gcd.GcdValueList getGCDList(
        @WebParam(partName = "GCDKey1", name = "gcdKey", targetNamespace = "http://www.ynm.com/schema/gcd")
        java.lang.String gcdKey1
    );

    @WebResult(name = "gcdValue", targetNamespace = "http://www.ynm.com/schema/gcd", partName = "GCDResponse")
    @WebMethod(action = "http://www.pluralsight.com/service/gcd/get")
    public int getGCD(
        @WebParam(partName = "GCDKey", name = "gcdKey", targetNamespace = "http://www.ynm.com/schema/gcd")
        java.lang.String gcdKey
    );

    @WebResult(name = "gcdSum", targetNamespace = "http://www.ynm.com/schema/gcd", partName = "GCDSumResponse")
    @WebMethod(action = "http://www.pluralsight.com/service/gcd/getSum")
    public int getGCDSum(
        @WebParam(partName = "GCDKey2", name = "gcdKey", targetNamespace = "http://www.ynm.com/schema/gcd")
        java.lang.String gcdKey2
    );
}
