package com.ynm.service.gcd;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * The port type of the WSDL is the first element we
 * 			will focus on. This element is comparable
 * 			to an interface. It defines
 * 			the type or types of services that are
 * 			available. As part of
 * 			generation, the port type has been given the name GCD to uniquely
 * 			identify it
 * 			in the document.
 * 		
 *
 * This class was generated by Apache CXF 2.7.8
 * 2017-07-01T18:37:31.746+10:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://www.ynm.com/service/gcd/", name = "GCDInterface")
@XmlSeeAlso({com.ynm.schema.gcd.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GCDInterface {

    @WebResult(name = "gcdValueList", targetNamespace = "http://www.ynm.com/schema/gcd", partName = "GCDValueListResponse")
    @WebMethod(action = "http://www.pluralsight.com/service/gcdList")
    public com.ynm.schema.gcd.GcdValueList gcdList();

    @WebResult(name = "gcdSum", targetNamespace = "http://www.ynm.com/schema/gcd", partName = "GCDSumResponse")
    @WebMethod(action = "http://www.pluralsight.com/service/gcdSum")
    public int gcdSum();

    @WebResult(name = "gcdValue", targetNamespace = "http://www.ynm.com/schema/gcd", partName = "GCDResponse")
    @WebMethod(action = "http://www.pluralsight.com/service/gcd")
    public int gcd();
}
